#!/usr/bin/env python3
"""Generate exact integer gain steps for the observed Wine DirectSound backend.

Wine 10 DSOUND_RecalcVolPan quantizes 65535 * 2**(centidb/600) to DWORD;
DSOUND_MixerVol converts that integer to Float32 by division by 65535.
https://raw.githubusercontent.com/wine-mirror/wine/wine-10.0/dlls/dsound/mixer.c
This is a backend calibration, not a claim of Windows hardware equivalence.
"""
import argparse
from decimal import Decimal, localcontext
from pathlib import Path

OUTPUT = Path(__file__).resolve().parent.parent / "re_out/dd2_sound_gain.h"


def gains():
    with localcontext() as context:
        context.prec = 60
        log2 = Decimal(2).ln()
        return [int(Decimal(65535) * (-Decimal(i)*log2/600).exp()) for i in range(9600)]


def render():
    values = gains()
    rows = ["    " + ",".join(map(str, values[i:i+16])) + "," for i in range(0, len(values), 16)]
    return ("/* Generated by tools/generate_sound_gain.py. Exact quantized attenuation\n"
            " * for the observed Wine backend; -9600 centidB and below quantize to zero. */\n"
            "static const unsigned short dd2_sound_gain[9600] = {\n" + "\n".join(rows) + "\n};\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if OUTPUT.read_text() != expected:
            raise SystemExit("Generated sound gain table differs; run tools/generate_sound_gain.py")
        print("PASS all 9600 quantized gain entries reproduce exactly")
    else:
        OUTPUT.write_text(expected)


if __name__ == "__main__":
    main()
