#!/usr/bin/env python3
"""Verify actual championship application ownership, results and presentation.

Natural ten-lap sessions use ordinary AI analog controls through the production
application library. Native X11 and real Chromium canvas pixels must match the
application framebuffer. All twenty rendered standings, names and points are
checked. This is first-round integration, not full campaigns or original parity.
"""
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone
from functools import partial
from http.server import ThreadingHTTPServer
import argparse
import hashlib
import json
import os
from pathlib import Path
import struct
import subprocess
import sys
import threading

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from artifacts import WORK, check_space, prepare_output, run_bounded
from rewrite.quality import ROOT
from rewrite.serve import Handler, FILES
from rewrite.verify_archive import ORIGINAL_SHA256
from rewrite.verify_championship import IMAGE_SHA256, check_session, digest, write_json
from rewrite.verify_window import NativeWindow, build_sanitized

# Public five-by-seven bitmap typography used by the temporary front end.
# Check every foreground/background cell, rather than one lit pixel or a hash
# generated by calling the same draw function a second time.
CHARTS = [
    [14,17,19,21,25,17,14], [4,12,4,4,4,4,14], [14,17,1,2,4,8,31],
    [30,1,1,14,1,1,30], [2,6,10,18,31,2,2], [31,16,16,30,1,1,30],
    [14,16,16,30,17,17,14], [31,1,2,4,8,8,8], [14,17,17,14,17,17,14],
    [14,17,17,15,1,1,14], [14,17,17,31,17,17,17], [30,17,17,30,17,17,30],
    [14,17,16,16,16,17,14], [30,17,17,17,17,17,30], [31,16,16,30,16,16,31],
    [31,16,16,30,16,16,16], [14,17,16,23,17,17,15], [17,17,17,31,17,17,17],
    [14,4,4,4,4,4,14], [7,2,2,2,2,18,12], [17,18,20,24,20,18,17],
    [16,16,16,16,16,16,31], [17,27,21,21,17,17,17], [17,25,21,19,17,17,17],
    [14,17,17,17,17,17,14], [30,17,17,30,16,16,16], [14,17,17,17,21,18,13],
    [30,17,17,30,20,18,17], [15,16,16,14,1,1,30], [31,4,4,4,4,4,4],
    [17,17,17,17,17,17,14], [17,17,17,17,17,10,4], [17,17,17,21,21,21,10],
    [17,17,10,4,10,17,17], [17,17,10,4,4,4,4], [31,1,2,4,8,16,31],
    [1,1,2,4,8,16,16], [0,4,4,0,4,4,0], [0,0,0,0,0,4,4], [0]*7]
FONT = dict(zip('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ/:. ', CHARTS))
BACKGROUND, WHITE, YELLOW = (10,18,31), (224,224,224), (255,255,0)


def word(image, text, left, bottom, color):
    for index, character in enumerate(text.upper()):
        chart = FONT[character]
        for row, bits in enumerate(chart):
            for column in range(5):
                expected = color if bits & (1 << (4-column)) else BACKGROUND
                point = (left + index*6 + column, 479 - (bottom + 6-row))
                if image.getpixel(point) != expected:
                    raise ValueError(f'Visible text {text!r} differs at {point}: '
                                     f'{image.getpixel(point)} != {expected}')


def check_pixels(directory, rows, names, mode, missing):
    standings = next(row['drivers'] for row in rows if row['kind'] == 'standings')
    result = next(row for row in rows if row['kind'] == 'result')
    if len(standings) != 20:
        raise ValueError('Missing twenty-driver standings')
    # Initial division assignment is independent of the actual result ordering.
    # Stable driver ID is the original tie break after points.
    original_order = [0,6,15,12,9,17,5,18,13,19,11,2,8,14,4,10,1,16,3,7]
    initial_divisions = [3-original_order.index(driver)//5 for driver in range(20)]
    for driver, (division, rank, points) in enumerate(standings):
        expected_rank = sum(initial_divisions[rival] == division and
                            (result['drivers'][rival][3] > points or
                             (result['drivers'][rival][3] == points and rival < driver))
                            for rival in range(20))
        if division != initial_divisions[driver] or rank != expected_rank or points != result['drivers'][driver][3]:
            raise ValueError('Visible league input differs from independent score/tie ordering')
    image = Image.open(directory / 'results.ppm').convert('RGB')
    word(image, 'STOCKCAR CHAMPIONSHIP' if mode == 1 else 'WRECKING CHAMPIONSHIP', 32, 438, WHITE)
    word(image, 'ROUND COMPLETE', 32, 94, YELLOW)
    word(image, 'ENTER TO CONTINUE   ESC TO LEAVE', 32, 44, YELLOW)
    for division in range(4):
        left, bottom = 32 + (division%2)*296, 362 - (division//2)*142
        word(image, 'DIVISION', left, bottom, WHITE)
        word(image, str(division+1), left+60, bottom, WHITE)
    for driver, (division, rank, points) in enumerate(standings):
        left, bottom = 32 + (division%2)*296, 362 - (division//2)*142 - (rank+1)*18
        color = YELLOW if driver == 0 else WHITE
        word(image, str(rank+1), left, bottom, color)
        word(image, names[driver], left+18, bottom, color)
        word(image, str(points), left+228, bottom, color)
    for name, round_number, points, bottom in [('start',1,0,6), ('results',1,standings[0][2],408)]:
        current = Image.open(directory / (name+'.ppm')).convert('RGB')
        for label, value, left in [('SEASON',1,30), ('RACE',round_number,176),
                                   ('DIVISION',4,298), ('POINTS',points,440)]:
            word(current,label,left,bottom,WHITE)
            word(current,str(value),left+60,bottom,WHITE)
    if missing:
        if (directory/'results.ppm').read_bytes() != (directory/'retained.ppm').read_bytes():
            raise ValueError('Preparation failure changed visible results')
    else:
        next_image = Image.open(directory/'next.ppm').convert('RGB')
        word(next_image,'2',236,6,WHITE)
        word(next_image,str(standings[0][2]),500,6,WHITE)
    return {'pass_':True, 'all_twenty_names_ranks_scores':True,
            'metadata_round_points':True, 'preparation_rollback':missing,
            'images_sha256':{p.name:digest(p) for p in directory.glob('*.ppm')}}


HTML = '''<!doctype html><html lang="en"><link rel="icon" href="data:,">
<button id="start" disabled>Start verification</button><canvas id="canvas" width="640" height="480"></canvas>
<script>
var ready=false,started=false;
var Module={canvas:document.querySelector('#canvas'),noInitialRun:true,
 print:message=>console.log(message),printErr:message=>console.error(message),
 onRuntimeInitialized:()=>{ready=true;document.querySelector('#start').disabled=false;}};
document.querySelector('#start').onclick=async()=>{
 const query=new URLSearchParams(location.search);
 const bytes=new Uint8Array(await (await fetch('/fixture/'+query.get('fixture'))).arrayBuffer());
 Module.FS.writeFile('/Dirinfo',bytes);Module.FS.mkdir('/captures');
 Module.callMain(['/Dirinfo',query.get('mode'),query.get('fixture'),'/captures']);
 started=true;
};
</script><script async src="dd2_championship_application_export.js"></script></html>'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, default=WORK/'rewrite-championship-application')
    parser.add_argument('--native-build-dir', type=Path, default=WORK/'rewrite-native')
    parser.add_argument('--wasm-build-dir', type=Path, default=WORK/'rewrite-wasm')
    args = parser.parse_args()
    output = prepare_output(args.output)
    if WORK not in output.parents:
        parser.error('Use /tmp/wasm-dd2/')
    output.mkdir(parents=True, exist_ok=True)
    check_space(output)
    archive = (ROOT/'DestructionDerby2/Dirinfo').resolve()
    image_path = ROOT/'DestructionDerby2/dd2_image.bin'
    if digest(archive) != ORIGINAL_SHA256 or digest(image_path) != IMAGE_SHA256:
        raise ValueError('Provision supported unmodified original files')
    image = image_path.read_bytes()
    names = ['PLAYER'] + [image[0x67654+i*16:0x67654+(i+1)*16].split(b'\0',1)[0].decode('ascii') for i in range(1,20)]
    tables = {0:list(struct.unpack_from('<20H',image,0x6762c)),1:list(struct.unpack_from('<20H',image,0x67604))}
    data = bytearray(archive.read_bytes())
    row = data[:0x2808].find(b'LEV2\\LEVEL.DAT\0')
    if row < 0 or row%24:
        raise ValueError('Missing original next-track directory row')
    data[row] = ord('Z')
    missing_archive = output/'missing-next-Dirinfo'
    missing_archive.write_bytes(data)
    del data
    sanitized_dir = output/'sanitized'
    sanitized_dir.mkdir(exist_ok=True)
    sanitized = build_sanitized(sanitized_dir, ROOT/'tests/championship_application_export.c')
    sources = [p for folder in ('src','tests') for p in (ROOT/folder).rglob('*') if p.suffix in ('.c','.h','.js','.html')]
    sources += [p for p in (ROOT/'tools/rewrite').glob('*') if p.suffix in ('.py','.js')]
    sources += [ROOT/'CMakeLists.txt',ROOT/'.clang-format',ROOT/'.clang-tidy']
    native = args.native_build_dir.resolve()/'dd2_championship_application_export'
    wasm = args.wasm_build_dir.resolve()/'dd2_championship_application_export'
    binaries = [native, sanitized, Path(str(wasm)+'.js'), Path(str(wasm)+'.wasm'),
                WORK/'rewrite-native/softgl/libsoftgl.a']
    worker = Path(str(wasm)+'.worker.js')
    if worker.exists():
        binaries.append(worker)
    identity = {'scope':__doc__.strip(),'original_sha256':digest(archive),
                'image_sha256':digest(image_path),'missing_fixture_sha256':digest(missing_archive),
                'source_sha256':{str(p.relative_to(ROOT)):digest(p) for p in sources},
                'binary_sha256':{str(p):digest(p) for p in binaries},
                'sanitizer_build':json.loads((sanitized_dir/'sanitizer-build.json').read_text())}
    write_json(output/'identity.json',identity)
    class HarnessHandler(Handler):
        def do_GET(self):
            route = self.path.split('?',1)[0]
            if route == '/harness.html':
                body = HTML.encode()
                self.send_response(200);self.send_header('Content-Type','text/html')
                self.send_header('Content-Length',str(len(body)));self.end_headers();self.wfile.write(body)
            elif route in ('/fixture/next','/fixture/missing'):
                content = (missing_archive if route.endswith('missing') else archive).read_bytes()
                self.send_response(200);self.send_header('Content-Length',str(len(content)))
                self.end_headers();self.wfile.write(content)
            elif route in FILES or route.startswith('/dd2_championship_application_export.'):
                # The private server exposes only named generated build files.
                from http.server import SimpleHTTPRequestHandler
                SimpleHTTPRequestHandler.do_GET(self)
            else:
                self.send_error(404)
    server = ThreadingHTTPServer(('127.0.0.1',0),partial(HarnessHandler,directory=str(args.wasm_build_dir.resolve())))
    thread = threading.Thread(target=server.serve_forever,daemon=True)
    thread.start()
    url = f'http://127.0.0.1:{server.server_port}'

    def check_case(case):
        target, mode_name, mode, missing = case
        name = target+'-'+mode_name+('-missing' if missing else '-next')
        directory = output/name
        directory.mkdir(exist_ok=True)
        selected_archive = missing_archive if missing else archive
        fixture = 'missing' if missing else 'next'
        log = directory/'run.log'
        error, presentation, command, returncode, rows, pixels = None, None, None, None, [], None
        try:
            if target == 'browser':
                command = ['node',str(ROOT/'tools/rewrite/verify_championship_application_browser.js'),
                           url,mode_name,fixture,str(directory)]
                with log.open('wb') as stream:
                    result = run_bounded(command,directory=output,timeout=1200,cwd=ROOT,
                                         stdout=stream,stderr=subprocess.STDOUT)
                returncode = result.returncode
                presentation = json.loads((directory/'canvas.json').read_text())
                if not presentation['pass_']:
                    raise ValueError('Actual canvas presentation failed')
            else:
                binary = sanitized if target == 'sanitized' else native
                arguments = [str(selected_archive),mode_name,fixture,str(directory),'observe']
                command = [str(binary),*arguments]
                ui = NativeWindow(directory,selected_archive,binary,label='run',arguments=arguments,input_pipe=True)
                ui.env['SDL_AUDIODRIVER'] = 'dummy'
                ui.env['ASAN_OPTIONS'] = 'detect_leaks=1:halt_on_error=1'
                ui.env['UBSAN_OPTIONS'] = 'halt_on_error=1:print_stacktrace=1'
                try:
                    ui.start()
                    expected_size = len(b'P6\n640 480\n255\n') + 640*480*3
                    ui.wait(lambda:(directory/'results.ppm').exists() and
                            (directory/'results.ppm').stat().st_size == expected_size,timeout=1200)
                    expected = Image.open(directory/'results.ppm').convert('RGB')
                    presentation = ui.match(expected,'natural-championship-results')
                    ui.process.stdin.write(b'\n');ui.process.stdin.flush();ui.process.stdin.close()
                    returncode = ui.process.wait(timeout=60)
                finally:
                    ui.close()
            content = log.read_text(errors='replace')
            if returncode != 0 or 'Sanitizer:' in content or 'runtime error:' in content:
                raise ValueError('Application process failed')
            rows = check_session(content,mode,missing,tables)
            pixels = check_pixels(directory,rows,names,mode,missing)
        except (ValueError,RuntimeError,TimeoutError,subprocess.TimeoutExpired,OSError) as exception:
            error = str(exception)
        receipt = {'identity':'../identity.json','target':target,'mode':mode_name,'missing':missing,
                   'command':command,'returncode':returncode,'pass_':error is None,'error':error,
                   'log_sha256':digest(log),'rows':rows,'presentation':presentation,'pixels':pixels}
        write_json(directory/'receipt.json',receipt)
        if error is None:
            log.unlink()
            for capture in directory.glob('*.ppm'):
                capture.unlink()
        print(json.dumps({'case':name,'pass_':error is None,'error':error}),flush=True)
        return receipt

    cases = [(target,name,mode,missing) for target in ('native','browser','sanitized')
             for name,mode,missing in [('stock',1,False),('wreck',0,False),('stock',1,True)]]
    try:
        with ThreadPoolExecutor(max_workers=3) as executor:
            receipts = list(executor.map(check_case,cases))
    finally:
        server.shutdown();server.server_close();thread.join(timeout=5)
    source_unchanged = all(digest(ROOT/name)==value for name,value in identity['source_sha256'].items())
    binary_unchanged = all(digest(Path(name))==value for name,value in identity['binary_sha256'].items())
    report = {'identity':'identity.json','scope':__doc__.strip(),
              'verified_at':datetime.now(timezone.utc).isoformat(),
              'pass_':source_unchanged and binary_unchanged and all(r['pass_'] for r in receipts),
              'source_unchanged':source_unchanged,'binary_unchanged':binary_unchanged,
              'full_game_acceptance':False,'results':receipts}
    write_json(output/'report.json',report)
    missing_archive.unlink()
    sanitized.unlink()
    check_space(output)
    if not report['pass_']:
        raise RuntimeError('Application verification failed; see '+str(output/'report.json'))
    (sanitized_dir/'sanitizer-build.log').unlink()
    print(json.dumps({'pass_':True,'report':str(output/'report.json')}),flush=True)


if __name__ == '__main__':
    main()
